version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: _test\.go
        text: SA1019
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value.*is not checked
        source: defer.*\(.*\)
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
